using OpenFleet.Domain.Entities;
using OpenFleet.Domain.Enums;

namespace OpenFleet.Tests.Domain;

public class VehicleTests
{
    [Fact]
    public void Vehicle_DefaultStatus_IsActive()
    {
        var vehicle = new Vehicle();
        Assert.Equal(VehicleStatus.Active, vehicle.Status);
    }

    [Fact]
    public void Vehicle_Id_IsAutoGenerated()
    {
        var vehicle = new Vehicle();
        Assert.NotEqual(Guid.Empty, vehicle.Id);
    }

    [Fact]
    public void Vehicle_CreatedAt_IsSetToUtcNow()
    {
        var before = DateTime.UtcNow.AddSeconds(-1);
        var vehicle = new Vehicle();
        var after = DateTime.UtcNow.AddSeconds(1);

        Assert.True(vehicle.CreatedAt >= before && vehicle.CreatedAt <= after);
    }

    [Fact]
    public void Vehicle_CanSetProperties()
    {
        var vehicle = new Vehicle
        {
            VIN = "1HGBH41JXMN109186",
            Make = "Ford",
            Model = "F-150",
            Year = 2022,
            Status = VehicleStatus.InMaintenance
        };

        Assert.Equal("1HGBH41JXMN109186", vehicle.VIN);
        Assert.Equal("Ford", vehicle.Make);
        Assert.Equal("F-150", vehicle.Model);
        Assert.Equal(2022, vehicle.Year);
        Assert.Equal(VehicleStatus.InMaintenance, vehicle.Status);
    }

    [Fact]
    public void WorkOrder_DefaultStatus_IsOpen()
    {
        var workOrder = new WorkOrder();
        Assert.Equal(WorkOrderStatus.Open, workOrder.Status);
    }

    [Fact]
    public void WorkOrder_DefaultPriority_IsMedium()
    {
        var workOrder = new WorkOrder();
        Assert.Equal(WorkOrderPriority.Medium, workOrder.Priority);
    }

    [Fact]
    public void User_CanSetRole()
    {
        var user = new User { Role = UserRole.FleetManager };
        Assert.Equal(UserRole.FleetManager, user.Role);
    }

    [Fact]
    public void Part_UnitCost_CanBeSetAsDecimal()
    {
        var part = new Part { UnitCost = 49.99m };
        Assert.Equal(49.99m, part.UnitCost);
    }

    [Fact]
    public void Inspection_Passed_DefaultsToFalse()
    {
        var inspection = new Inspection();
        Assert.False(inspection.Passed);
    }

    [Fact]
    public void Asset_DefaultStatus_IsAvailable()
    {
        var asset = new Asset();
        Assert.Equal(AssetStatus.Available, asset.Status);
    }
}
